services:
  traefik:
    image: traefik:v2.10
    command:
      - --api
      - --providers.docker
      - --entrypoints.web.address=:80
      - --entrypoints.websecure.address=:443
      - --entrypoints.web.http.redirections.entryPoint.to=websecure
      - --entrypoints.web.http.redirections.entryPoint.scheme=https
      - --certificatesresolvers.myresolver.acme.tlschallenge=true
      - --certificatesresolvers.myresolver.acme.email=iwekasomex61@gmail.com
      - --certificatesresolvers.myresolver.acme.storage=/letsencrypt/acme.json
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - "./acme.json:/letsencrypt/acme.json"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.traefik.rule=Host(`traefik.hngprog.biz`)"
      - "traefik.http.routers.traefik.service=api@internal"
      - "traefik.http.routers.traefik.entrypoints=websecure"
      - "traefik.http.routers.traefik.tls.certresolver=myresolver"
      - "traefik.http.routers.traefik.middlewares=auth"
      - "traefik.http.middlewares.auth.basicauth.users=somex:$$2y$$10$$6Lf3ixHBeAShv2CwZcHlN.YuXQ024CqXE1ui.tpRWrDyydpVYtzge"
    networks:
      - app-net
  frontend:
    build: ./frontend
    container_name: frontend
    environment:
      - AUTH_API_ADDRESS=http://auth-api:8081
      - TODOS_API_ADDRESS=http://todos-api:8082
      - PORT=8080
      - ZIPKIN_URL=http://zipkin:9411
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.frontend.rule=Host(`stage-4.hngprog.biz`)"
      - "traefik.http.routers.frontend.entrypoints=websecure"
      - "traefik.http.routers.frontend.tls.certresolver=myresolver"
      - "traefik.http.services.frontend.loadbalancer.server.port=8080"
    networks:
      - app-net

  auth-api:
    build: 
      context: ./auth-api  
      dockerfile: Dockerfile
    container_name: auth-api
    environment:
      - AUTH_API_PORT=8081
      - USERS_API_ADDRESS=http://users-api:8083
      - JWT_SECRET=myfancysecret
    labels:
      - "traefik.enable=true"
      - traefik.http.routers.auth-api.rule=PathPrefix(`/api/auth`)
      - "traefik.http.routers.auth-api.entrypoints=websecure"
      - "traefik.http.routers.auth-api.tls=true"
      - "traefik.http.routers.auth-api.tls.certresolver=myresolver"
    ports:
      - "8081:8081"
    networks:
      - app-net

  users-api:
    build: 
      context: ./users-api  
      dockerfile: Dockerfile
    container_name: users-api
    environment:
      - JWT_SECRET=myfancysecret
      - SERVER_PORT=8083
      - traefik.enable=true
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.users-api.rule=PathPrefix(`/api/users`)"
      - "traefik.http.routers.users-api.entrypoints=websecure"
      - "traefik.http.routers.users-api.tls=true"
      - "traefik.http.routers.users-api.tls.certresolver=myresolver"
    ports:
      - "8083:8083"
    networks:
      - app-net
  todos-api:
    build: 
      context: ./todos-api  
      dockerfile: Dockerfile
    container_name: todos-api
    ports:
      - "8082:8082"
    environment:
      - JWT_SECRET=myfancysecret
      - REDIS_HOST=redis-queue
      - REDIS_PORT=6379
      - REDIS_CHANNEL=log_channel
      - TODO_API_PORT=8082
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.todos-api.rule=PathPrefix(`/api/todos`)"
      - "traefik.http.routers.todos-api.entrypoints=websecure"
      - "traefik.http.routers.todos-api.tls=true"
      - "traefik.http.routers.todos-api.tls.certresolver=myresolver"
      - "traefik.http.middlewares.todos-stripprefix.stripprefix.prefixes=/api/todos"
      - "traefik.http.routers.todos-api.middlewares=todos-stripprefix"

    networks:
      - app-net

  log-message-processor:
    build: 
      context: ./log-message-processor  
      dockerfile: Dockerfile
    container_name: log-message-processor
    ports:
      - "8090:8090"
    environment:
      - REDIS_HOST=redis-queue
      - REDIS_PORT=6379
      - REDIS_CHANNEL=log_channel
    networks:
      - app-net

  redis-queue:
    image: redis:alpine
    container_name: redis-queue
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    restart: unless-stopped
    networks:
      - app-net
  zipkin:
    image: openzipkin/zipkin
    container_name: zipkin
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.zipkin.rule=PathPrefix(`/api/zipkin`)"
      - "traefik.http.routers.zipkin.entrypoints=websecure"
      - "traefik.http.routers.zipkin.tls=true"
      - "traefik.http.routers.zipkin.tls.certresolver=myresolver"
      - "traefik.http.middlewares.zipkin-stripprefix.stripprefix.prefixes=/api/zipkin"
      - "traefik.http.routers.zipkin.middlewares=zipkin-stripprefix"
    ports:
      - "9411:9411"
    networks:
      - app-net
networks:
  app-net:
    driver: bridge

volumes:
  redis-data:
  letsencrypt: